name: book
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image:
  flutter_svg:
  shared_preferences: ^2.2.1
  intl:
  flutter_bloc:
  connectivity:
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  fpdart: ^1.1.0
  dartz: ^0.10.1
  share_plus: ^7.1.0
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.0.4
  image_cropper:
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  flutter_facebook_auth:
  google_sign_in: ^6.1.5
  go_router: ^11.1.3
  flutter_paypal: ^0.2.0
  flutter_windowmanager: ^0.2.0
  get_storage: ^2.1.1
  package_info_plus: ^4.2.0
  grouped_list: ^5.1.2
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_bg.png"

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
        - asset: assets/fonts/OutfitThin.ttf
          weight: 100
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500
        - asset: assets/fonts/OutfitLight.ttf
          weight: 300
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
